### ISSUE TITLE
"null island" bounding boxes for several layers

### ISSUE THREAD

**Issue by drh-stanford** [OpenGeoMetadata/edu.nyu#17]
For example: https://earthworks.stanford.edu/catalog/nyu-2451-36796.json has:

```
"solr_geom": "ENVELOPE(0, 0, 0, 0)",
```

There are 12 of them that you can see here:

  https://earthworks.stanford.edu/?f%5Baccess%5D%5B%5D=unavailable&f%5Bdct_provenance_s%5D%5B%5D=NYU&q=

**Comment by sgbalogh** [comment]
@drh-stanford thanks for the heads up –– I'll try to figure out the underlying cause and push up some corrected metadata...

**Comment by andrewbattista** [comment]
The metadata for these is taken care of. Thanks @drh-stanford for this ticket.
