### ISSUE TITLE
Question about HTTP vs HTTPS urls

### ISSUE THREAD

**Issue by mejackreed** [OpenGeoMetadata/edu.nyu#4]
Currently within the NYU repo there are occurrences of `http://maps-public.geo.nyu.edu/geoserver/sdr`

Is that correct or should it be an HTTPS version of that url?

``` sh
$ grep -nr 'http://maps-public.geo.nyu.edu/geoserver/sdr/wms' . | wc -l
      49
```

**Comment by sgbalogh** [comment]
No, those are old –– they should all be HTTPS. Thanks for the heads up, I'll make the change.

**Comment by sgbalogh** [comment]
Fixed in https://github.com/OpenGeoMetadata/edu.nyu/commit/82ad218f258b7ad1c2b39572d5a7fdad6acbe5d7
